import { Inter } from "next/font/google";
import "./globals.css";
import Links from "@/components/NavigationLinks/Links";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Education jobs blog page",
  description: "Generated by Ayush Tiwari",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Links/>
        {children}</body>
    </html>
  );
}
